---
- name: Commit Files to GitHub
  hosts: localhost

  tasks:
    - name: Clone GitHub Repository
      git:
        repo: git@github.com:Akhila271999/automation.git
        dest: ~ /aws_scripts/repository
        clone: yes

    - name: Copy Files to Local Repository
      copy:
        src: ~ /aws_scripts
        dest: ~ /home/ec2-user/automation/automation.git

    - name: Commit Files
      shell: |
        cd /aws_scripts/repository
        git add .
        git commit -m "Adding files"
        git push origin master

